apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-platform-kafka-admins
  namespace: dev-platform-kafka
subjects:
- kind: Group
  name: etp-dev-platform-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-app-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-platform-flink-admins
  namespace: dev-platform-flink
subjects:
- kind: Group
  name: etp-dev-platform-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-app-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-data-team-writers
  namespace: dev-data-airflow
subjects:
- kind: Group
  name: etp-dev-data-engineers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-app-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-app-team-writers-ingestion
  namespace: dev-app-ingestion-api
subjects:
- kind: Group
  name: etp-dev-app-engineers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-app-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-app-team-writers-serving
  namespace: dev-app-serving-api
subjects:
- kind: Group
  name: etp-dev-app-engineers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-app-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-observability-readonly
  namespace: dev-ops-observability
subjects:
- kind: Group
  name: etp-dev-observers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-readonly
  apiGroup: rbac.authorization.k8s.io