apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: dev-platform-kafka
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: dev-platform-flink
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: dev-data-airflow
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "50"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: dev-app-ingestion-api
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "30"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: dev-app-serving-api
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "30"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: dev-ops-observability
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "40"