-- Bootstrap Snowflake source objects required by dbt staging models.
-- Target: SF_TUTS.ICEBERG_CUSTOMER_ANALYTICS

use role ACCOUNTADMIN;
use warehouse COMPUTE_WH;

create database if not exists SF_TUTS;
create schema if not exists SF_TUTS.ICEBERG_CUSTOMER_ANALYTICS;

create table if not exists SF_TUTS.ICEBERG_CUSTOMER_ANALYTICS.TABLEAU_REPORTING_EVENTS (
  EVENT_ID VARCHAR,
  EVENT_TYPE VARCHAR,
  EVENT_VERSION VARCHAR,
  EVENT_TIME VARCHAR,
  INGESTED_AT VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  TENANT_ID VARCHAR,
  MESSAGE_ID VARCHAR,
  CORRELATION_ID VARCHAR,
  TRACE_ID VARCHAR,
  ACTOR_TYPE VARCHAR,
  PAYLOAD VARCHAR,
  EVENT_TS TIMESTAMP_NTZ,
  INGESTED_TS TIMESTAMP_NTZ,
  EVENT_DATE DATE
);

create table if not exists SF_TUTS.ICEBERG_CUSTOMER_ANALYTICS.DIM_CUSTOMER_TENANT (
  TENANT_ID VARCHAR,
  FIRST_SEEN_AT TIMESTAMP_NTZ,
  LAST_SEEN_AT TIMESTAMP_NTZ,
  TOTAL_EVENTS NUMBER(38,0)
);

create table if not exists SF_TUTS.ICEBERG_CUSTOMER_ANALYTICS.DIM_CUSTOMER_EVENT_TYPE (
  EVENT_TYPE VARCHAR,
  FIRST_SEEN_AT TIMESTAMP_NTZ,
  LAST_SEEN_AT TIMESTAMP_NTZ,
  TOTAL_EVENTS NUMBER(38,0)
);

create table if not exists SF_TUTS.ICEBERG_CUSTOMER_ANALYTICS.FCT_TABLEAU_DAILY_CUSTOMER_DELIVERY (
  TENANT_ID VARCHAR,
  EVENT_DATE DATE,
  REQUESTED_COUNT NUMBER(38,0),
  DISPATCHED_COUNT NUMBER(38,0),
  DELIVERED_COUNT NUMBER(38,0),
  OPENED_COUNT NUMBER(38,0),
  CLICKED_COUNT NUMBER(38,0)
);
