apiVersion: v1
kind: Namespace
metadata:
  name: prod-platform-kafka
  labels:
    environment: prod
    domain: platform
    workload: kafka
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-platform-flink
  labels:
    environment: prod
    domain: platform
    workload: flink
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-data-airflow
  labels:
    environment: prod
    domain: data
    workload: airflow
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-app-ingestion-api
  labels:
    environment: prod
    domain: app
    workload: ingestion-api
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-app-serving-api
  labels:
    environment: prod
    domain: app
    workload: serving-api
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-ops-observability
  labels:
    environment: prod
    domain: ops
    workload: observability
    pod-security.kubernetes.io/enforce: restricted