apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: prod-platform-kafka
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 48Gi
    limits.cpu: "40"
    limits.memory: 96Gi
    persistentvolumeclaims: "40"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: prod-platform-flink
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 48Gi
    limits.cpu: "40"
    limits.memory: 96Gi
    persistentvolumeclaims: "40"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: prod-data-airflow
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "120"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: prod-app-ingestion-api
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "100"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: prod-app-serving-api
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "100"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: prod-ops-observability
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "120"