apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging-platform-kafka
spec:
  limits:
  - type: Container
    default:
      cpu: "1500m"
      memory: "3Gi"
    defaultRequest:
      cpu: "300m"
      memory: "768Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging-platform-flink
spec:
  limits:
  - type: Container
    default:
      cpu: "1500m"
      memory: "3Gi"
    defaultRequest:
      cpu: "300m"
      memory: "768Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging-data-airflow
spec:
  limits:
  - type: Container
    default:
      cpu: "750m"
      memory: "1536Mi"
    defaultRequest:
      cpu: "150m"
      memory: "384Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging-app-ingestion-api
spec:
  limits:
  - type: Container
    default:
      cpu: "750m"
      memory: "1536Mi"
    defaultRequest:
      cpu: "150m"
      memory: "384Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging-app-serving-api
spec:
  limits:
  - type: Container
    default:
      cpu: "750m"
      memory: "1536Mi"
    defaultRequest:
      cpu: "150m"
      memory: "384Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging-ops-observability
spec:
  limits:
  - type: Container
    default:
      cpu: "1500m"
      memory: "3Gi"
    defaultRequest:
      cpu: "300m"
      memory: "768Mi"